//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Model
{
    using QLSV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class DangNhap :BaseViewModel
    {
        private string _Ten;
        public string Ten { get => _Ten; set { _Ten = value; OnPropertyChanged(); } }

        private string _TaiKhoan;
        public string TaiKhoan { get => _TaiKhoan; set { _TaiKhoan = value; OnPropertyChanged(); } }

        private string _MatKhau;
        public string MatKhau { get => _MatKhau; set { _MatKhau = value; OnPropertyChanged(); } }

        public Nullable<bool> _Cap_TK;
        public Nullable<bool> Cap_TK { get => _Cap_TK; set { _Cap_TK = value; OnPropertyChanged(); } }
    }
}
