//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Model
{
    using QLSV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LopSH : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopSH()
        {
            this.SinhViens = new HashSet<SinhVien>();
        }


        private string _Ma_Lop;
        public string Ma_Lop { get => _Ma_Lop; set { _Ma_Lop = value; OnPropertyChanged(); } }

        private int _Ma_GV;
        public int Ma_GV { get => _Ma_GV; set { _Ma_GV = value; OnPropertyChanged(); } }

        private GiangVien _GiangVien;
        public virtual GiangVien GiangVien { get => _GiangVien; set { _GiangVien = value; OnPropertyChanged(); } }
        
        public virtual ICollection<SinhVien> SinhViens { get; set; }
    }
}
