//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Model
{
    using QLSV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc :BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonHoc()
        {
            this.PhieuDiems = new HashSet<PhieuDiem>();
        }

        private int _Ma_Mon;
        public int Ma_Mon { get => _Ma_Mon; set { _Ma_Mon = value; OnPropertyChanged(); } }

        private string _TenMon;
        public string TenMon { get => _TenMon; set { _TenMon = value; OnPropertyChanged(); } }

        private int _SoChi;
        public int SoChi { get => _SoChi; set { _SoChi = value; OnPropertyChanged(); } }

        private int _Ma_GV;
        public int Ma_GV { get => _Ma_GV; set { _Ma_GV = value; OnPropertyChanged(); } }

        private GiangVien _GiangVien;
        public virtual GiangVien GiangVien { get => _GiangVien; set { _GiangVien = value; OnPropertyChanged(); } }

        public virtual ICollection<PhieuDiem> PhieuDiems { get; set; }
    }
}
