//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Model
{
    using QLSV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDiem :BaseViewModel
    {
        private int _Ma_Phieu;
        public int Ma_Phieu { get => _Ma_Phieu; set { _Ma_Phieu = value; OnPropertyChanged(); } }

        private int _Ma_SV;
        public int Ma_SV { get => _Ma_SV; set { _Ma_SV = value; OnPropertyChanged(); } }

        private int _Ma_Mon;
        public int Ma_Mon { get => _Ma_Mon; set { _Ma_Mon = value; OnPropertyChanged(); } }

        private double? _ChuyenCan;
        public double? ChuyenCan { get => _ChuyenCan; set { _ChuyenCan = value; OnPropertyChanged(); } }

        private double? _GiuaKy;
        public double? GiuaKy { get => _GiuaKy; set { _GiuaKy = value; OnPropertyChanged(); } }

        private double? _CuoiKy;
        public double? CuoiKy { get => _CuoiKy; set { _CuoiKy = value; OnPropertyChanged(); } }

        private MonHoc _MonHoc;
        public virtual MonHoc MonHoc { get => _MonHoc; set { _MonHoc = value; OnPropertyChanged(); } }

        private SinhVien _SinhVien;
        public virtual SinhVien SinhVien { get => _SinhVien; set { _SinhVien = value; OnPropertyChanged(); } }

        private GiangVien _GiangVien;
        public virtual GiangVien GiangVien { get => _GiangVien; set { _GiangVien = value; OnPropertyChanged(); } }
    }
}
