//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Model
{
    using QLSV.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.PhieuDiems = new HashSet<PhieuDiem>();
        }

        private int _Ma_SV;
        public int Ma_SV { get => _Ma_SV; set { _Ma_SV = value; OnPropertyChanged(); } }

        private string _HoTen;
        public string HoTen { get => _HoTen; set { _HoTen = value; OnPropertyChanged(); } }

        private string _GioiTinh;
        public string GioiTinh { get => _GioiTinh; set { _GioiTinh = value; OnPropertyChanged(); } }

        private DateTime? _NgaySinh;
        public DateTime? NgaySinh { get => _NgaySinh; set { _NgaySinh = value; OnPropertyChanged(); } }

        private string _DiaChi;
        public string DiaChi { get => _DiaChi; set { _DiaChi = value; OnPropertyChanged(); } }

        private string _SDT;
        public string SDT { get => _SDT; set { _SDT = value; OnPropertyChanged(); } }

        private string _Email;
        public string Email { get => _Email; set { _Email = value; OnPropertyChanged(); } }

        private string _Ma_Lop;
        public string Ma_Lop { get => _Ma_Lop; set { _Ma_Lop = value; OnPropertyChanged(); } }

        private LopSH _LopSH;
        public virtual LopSH LopSH { get => _LopSH; set { _LopSH = value; OnPropertyChanged(); } }
        
        public virtual ICollection<PhieuDiem> PhieuDiems { get; set; }
    }
}
